// ─────────────────────────────────────────────
// iOS-inspired Design Tokens
// ─────────────────────────────────────────────

export const LIGHT_THEME = {
  bg:            '#F2F2F7',
  bgSecondary:   '#FFFFFF',
  bgTertiary:    '#E5E5EA',
  bgCard:        'rgba(255,255,255,0.85)',
  surface:       'rgba(255,255,255,0.72)',
  surfaceBlur:   'rgba(242,242,247,0.8)',
  text:          '#1C1C1E',
  textSecondary: '#3C3C43',
  textTertiary:  '#8E8E93',
  separator:     'rgba(60,60,67,0.12)',
  accent:        '#007AFF',
  accentSoft:    'rgba(0,122,255,0.12)',
  red:           '#FF3B30',
  green:         '#34C759',
  orange:        '#FF9500',
  purple:        '#AF52DE',
  pink:          '#FF2D55',
  teal:          '#5AC8FA',
  indigo:        '#5856D6',
  shadow:        'rgba(0,0,0,0.08)',
  shadowStrong:  'rgba(0,0,0,0.18)',
}

export const DARK_THEME = {
  bg:            '#000000',
  bgSecondary:   '#1C1C1E',
  bgTertiary:    '#2C2C2E',
  bgCard:        'rgba(28,28,30,0.92)',
  surface:       'rgba(44,44,46,0.72)',
  surfaceBlur:   'rgba(0,0,0,0.8)',
  text:          '#FFFFFF',
  textSecondary: '#EBEBF5',
  textTertiary:  '#8E8E93',
  separator:     'rgba(84,84,88,0.6)',
  accent:        '#0A84FF',
  accentSoft:    'rgba(10,132,255,0.18)',
  red:           '#FF453A',
  green:         '#32D74B',
  orange:        '#FF9F0A',
  purple:        '#BF5AF2',
  pink:          '#FF375F',
  teal:          '#64D2FF',
  indigo:        '#5E5CE6',
  shadow:        'rgba(0,0,0,0.4)',
  shadowStrong:  'rgba(0,0,0,0.7)',
}

/**
 * Generates a full style-object map from a theme token set.
 * This keeps inline styles consistent and co-located with tokens.
 */
export const buildStyles = (theme) => ({
  app: {
    fontFamily: "-apple-system, 'SF Pro Display', 'Helvetica Neue', sans-serif",
    background: theme.bg,
    color: theme.text,
    height: '100vh',
    display: 'flex',
    transition: 'background 0.3s, color 0.3s',
    overflow: 'hidden',
  },
  sidebar: {
    width: 260,
    background: theme.surface,
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderRight: `1px solid ${theme.separator}`,
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    position: 'sticky',
    top: 0,
    flexShrink: 0,
    zIndex: 10,
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minWidth: 0,
  },
  header: {
    padding: '16px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: `1px solid ${theme.separator}`,
    background: theme.surface,
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    position: 'sticky',
    top: 0,
    zIndex: 9,
    gap: 12,
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '20px 24px',
  },
  card: {
    background: theme.bgCard,
    borderRadius: 16,
    border: `1px solid ${theme.separator}`,
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    overflow: 'hidden',
  },
  input: {
    background: theme.bgTertiary,
    border: `1px solid ${theme.separator}`,
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: 15,
    color: theme.text,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  select: {
    background: theme.bgTertiary,
    border: `1px solid ${theme.separator}`,
    borderRadius: 10,
    padding: '10px 14px',
    paddingRight: 36,
    fontSize: 15,
    color: theme.text,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    cursor: 'pointer',
    appearance: 'none',
    WebkitAppearance: 'none',
  },
  textarea: {
    background: theme.bgTertiary,
    border: `1px solid ${theme.separator}`,
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: 15,
    color: theme.text,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    resize: 'vertical',
    minHeight: 80,
    transition: 'border-color 0.2s',
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: theme.textTertiary,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
    marginBottom: 6,
    display: 'block',
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    border: 'none',
    background: theme.bgTertiary,
    color: theme.text,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    transition: 'all 0.15s',
    flexShrink: 0,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    zIndex: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modal: {
    background: theme.bgSecondary,
    borderRadius: 20,
    border: `1px solid ${theme.separator}`,
    width: '100%',
    maxWidth: 500,
    maxHeight: '90vh',
    overflow: 'auto',
    boxShadow: `0 24px 60px ${theme.shadowStrong}`,
    animation: 'scaleIn 0.2s ease forwards',
  },
})

// Variant-based button styles
export const btnStyle = (theme, variant = 'primary') => ({
  border: 'none',
  borderRadius: 10,
  padding: '11px 20px',
  fontSize: 15,
  fontWeight: 600,
  cursor: 'pointer',
  transition: 'all 0.15s',
  fontFamily: 'inherit',
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 6,
  ...(variant === 'primary' && { background: theme.accent,     color: '#fff' }),
  ...(variant === 'ghost'   && { background: 'transparent',    color: theme.accent }),
  ...(variant === 'danger'  && { background: theme.red,        color: '#fff' }),
  ...(variant === 'secondary' && { background: theme.bgTertiary, color: theme.text }),
})

export const badgeStyle = (color) => ({
  display: 'inline-flex',
  alignItems: 'center',
  padding: '3px 8px',
  borderRadius: 6,
  fontSize: 11,
  fontWeight: 600,
  background: color + '22',
  color,
  letterSpacing: '0.3px',
  textTransform: 'uppercase',
})

export const dotStyle = (color) => ({
  width: 10,
  height: 10,
  borderRadius: '50%',
  background: color,
  display: 'inline-block',
  flexShrink: 0,
})